### ISSUE TITLE
Doppelstart

### ISSUE THREAD

**Issue by Loapu** [TRPG-Altis-Life/TRPG-Launcher#8]
Der Launcher startet bei der Installation doppelt

**Comment by T03RK3-Glenn** [comment]
Dieser Bug kann nicht  reproduziert werden! Bitte deinstallieren Sie den Launcher und installieren Sie ihn erneut. Sollte der Fehler bestehen bleiben, nehmen Sie den Installationsvorgang bitte auf oder setzten Sie sich mit uns in Kontakt!
